/*
 * Corpora API
 *
 * API for managing and processing corpora
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionTextMessage {
    #[serde(rename = "role")]
    pub role: String,
    #[serde(rename = "text")]
    pub text: String,
}

impl ChatCompletionTextMessage {
    pub fn new(role: String, text: String) -> ChatCompletionTextMessage {
        ChatCompletionTextMessage { role, text }
    }
}
