/*
 * Corpora API
 *
 * API for managing and processing corpora
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DraftBookResponse {
    #[serde(rename = "sections")]
    pub sections: Vec<models::DraftSection>,
}

impl DraftBookResponse {
    pub fn new(sections: Vec<models::DraftSection>) -> DraftBookResponse {
        DraftBookResponse { sections }
    }
}
