/*
 * Corpora API
 *
 * API for managing and processing corpora
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DraftSubsection {
    #[serde(rename = "subsection_id")]
    pub subsection_id: uuid::Uuid,
    #[serde(rename = "content")]
    pub content: String,
}

impl DraftSubsection {
    pub fn new(subsection_id: uuid::Uuid, content: String) -> DraftSubsection {
        DraftSubsection {
            subsection_id,
            content,
        }
    }
}
