/*
 * Corpora API
 *
 * API for managing and processing corpora
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LmStudioPing {
    #[serde(rename = "base_url")]
    pub base_url: String,
}

impl LmStudioPing {
    pub fn new(base_url: String) -> LmStudioPing {
        LmStudioPing { base_url }
    }
}
