/*
 * Corpora API
 *
 * API for managing and processing corpora
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RewriteSubsection {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl RewriteSubsection {
    pub fn new(id: uuid::Uuid, content: String) -> RewriteSubsection {
        RewriteSubsection {
            id,
            content,
            title: None,
        }
    }
}
