/*
 * Corpora API
 *
 * API for managing and processing corpora
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SectionOutline {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "order")]
    pub order: i32,
    #[serde(rename = "instructions")]
    pub instructions: String,
    #[serde(rename = "subsections")]
    pub subsections: Vec<models::SubsectionOutline>,
}

impl SectionOutline {
    pub fn new(
        title: String,
        order: i32,
        instructions: String,
        subsections: Vec<models::SubsectionOutline>,
    ) -> SectionOutline {
        SectionOutline {
            title,
            order,
            instructions,
            subsections,
        }
    }
}
