/*
 * Corpora API
 *
 * API for managing and processing corpora
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubsectionOutline {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "order")]
    pub order: i32,
    #[serde(rename = "instructions")]
    pub instructions: String,
}

impl SubsectionOutline {
    pub fn new(title: String, order: i32, instructions: String) -> SubsectionOutline {
        SubsectionOutline {
            title,
            order,
            instructions,
        }
    }
}
