/*
 * Corpora API
 *
 * API for managing and processing corpora
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct XaiModelsResponse {
    #[serde(rename = "models")]
    pub models: Vec<String>,
}

impl XaiModelsResponse {
    pub fn new(models: Vec<String>) -> XaiModelsResponse {
        XaiModelsResponse { models }
    }
}
