/*
 * Corpora API
 *
 * API for managing and processing corpora
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct XaiModelsRequest {
    /// Your xAI API key
    #[serde(rename = "api_key")]
    pub api_key: String,
    #[serde(
        rename = "base_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub base_url: Option<Option<String>>,
}

impl XaiModelsRequest {
    pub fn new(api_key: String) -> XaiModelsRequest {
        XaiModelsRequest {
            api_key,
            base_url: None,
        }
    }
}
