[package]
name = "corpora"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
corpora_client = { path = "../corpora_client" }
reqwest = "0.12.9"
serde_json = "1.0.133"
