/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import type { ClaudeModelsRequestBaseUrl } from "./claudeModelsRequestBaseUrl";

export interface ClaudeModelsRequest {
  /** Your Anthropic API key */
  api_key: string;
  /** Base URL for Anthropic API (defaults to https://api.anthropic.com) */
  base_url?: ClaudeModelsRequestBaseUrl;
}
