/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */

/**
 * only for providers that need a URL (e.g. local)
 */
export type CompletionRequestBaseUrl = string | null;
