/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */

/**
 * override env var for key-based providers
 */
export type CompletionRequestApiKey = string | null;
