/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import type { CompletionRequestBaseUrl } from "./completionRequestBaseUrl";
import type { CompletionRequestApiKey } from "./completionRequestApiKey";
import type { ChatMessageSchema } from "./chatMessageSchema";

export interface CompletionRequest {
  /** one of: openai, xai, local */
  provider: string;
  /** model name to use */
  model: string;
  /** only for providers that need a URL (e.g. local) */
  base_url?: CompletionRequestBaseUrl;
  /** override env var for key-based providers */
  api_key?: CompletionRequestApiKey;
  messages: ChatMessageSchema[];
}
