/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import type { CorpusSchemaUrl } from "./corpusSchemaUrl";

export interface CorpusSchema {
  name: string;
  url?: CorpusSchemaUrl;
}
