/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import type { CorpusResponseSchemaUrl } from "./corpusResponseSchemaUrl";

export interface CorpusResponseSchema {
  id: string;
  name: string;
  url?: CorpusResponseSchemaUrl;
  created_at: string;
  updated_at: string;
}
