/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import type { MessageSchema } from "./messageSchema";

export interface CorpusFileChatSchema {
  corpus_id: string;
  messages: MessageSchema[];
  voice?: string;
  purpose?: string;
  structure?: string;
  directions?: string;
  path: string;
}
