/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import type { DraftSubsection } from "./draftSubsection";

export interface DraftSection {
  /** UUID of the section */
  section_id: string;
  /** Plain text introduction for the section. No markdown headers. */
  introduction: string;
  /** List of drafted subsections, in order. */
  subsections: DraftSubsection[];
}
