/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */

export interface DraftSubsection {
  /** UUID of the subsection */
  subsection_id: string;
  /** Markdown content for this subsection. MUST start with '## {title}' where {title} is the subsection title. */
  content: string;
}
