/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import type { GenericCompletionRequestConfig } from "./genericCompletionRequestConfig";
import type { ChatCompletionTextMessage } from "./chatCompletionTextMessage";
import type { GenericCompletionRequestFieldsSchema } from "./genericCompletionRequestFieldsSchema";

export interface GenericCompletionRequest {
  provider: string;
  config: GenericCompletionRequestConfig;
  messages: ChatCompletionTextMessage[];
  fields_schema: GenericCompletionRequestFieldsSchema;
}
