/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import type { GenerateProjectImageInConfig } from "./generateProjectImageInConfig";
import type { GenerateProjectImageInPrompt } from "./generateProjectImageInPrompt";

export interface GenerateProjectImageIn {
  provider: string;
  config: GenerateProjectImageInConfig;
  caption: string;
  prompt?: GenerateProjectImageInPrompt;
}
