/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import type { ImageTokenOccurrenceSubsectionId } from "./imageTokenOccurrenceSubsectionId";
import type { ImageTokenOccurrenceSectionTitle } from "./imageTokenOccurrenceSectionTitle";
import type { ImageTokenOccurrenceSubsectionTitle } from "./imageTokenOccurrenceSubsectionTitle";

export interface ImageTokenOccurrence {
  section_id: string;
  subsection_id?: ImageTokenOccurrenceSubsectionId;
  section_title?: ImageTokenOccurrenceSectionTitle;
  subsection_title?: ImageTokenOccurrenceSubsectionTitle;
}
