/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import type { ImageTokenImageId } from "./imageTokenImageId";
import type { ImageTokenOccurrence } from "./imageTokenOccurrence";

export interface ImageToken {
  caption: string;
  fulfilled: boolean;
  image_id?: ImageTokenImageId;
  occurrences?: ImageTokenOccurrence[];
}
