/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectOutSubtitle } from "./projectOutSubtitle";
import type { ProjectOutPurpose } from "./projectOutPurpose";
import type { ProjectOutAuthor } from "./projectOutAuthor";
import type { ProjectOutPublisher } from "./projectOutPublisher";
import type { ProjectOutIsbn } from "./projectOutIsbn";
import type { ProjectOutLanguage } from "./projectOutLanguage";
import type { ProjectOutPublicationDate } from "./projectOutPublicationDate";
import type { ProjectOutInstructions } from "./projectOutInstructions";
import type { ProjectOutVoice } from "./projectOutVoice";

export interface ProjectOut {
  title: string;
  subtitle?: ProjectOutSubtitle;
  purpose?: ProjectOutPurpose;
  author?: ProjectOutAuthor;
  publisher?: ProjectOutPublisher;
  isbn?: ProjectOutIsbn;
  language?: ProjectOutLanguage;
  publication_date?: ProjectOutPublicationDate;
  instructions?: ProjectOutInstructions;
  voice?: ProjectOutVoice;
  id: number;
  created_at: string;
  updated_at: string;
}
