/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectUpdateTitle } from "./projectUpdateTitle";
import type { ProjectUpdateSubtitle } from "./projectUpdateSubtitle";
import type { ProjectUpdatePurpose } from "./projectUpdatePurpose";
import type { ProjectUpdateAuthor } from "./projectUpdateAuthor";
import type { ProjectUpdatePublisher } from "./projectUpdatePublisher";
import type { ProjectUpdateIsbn } from "./projectUpdateIsbn";
import type { ProjectUpdateLanguage } from "./projectUpdateLanguage";
import type { ProjectUpdatePublicationDate } from "./projectUpdatePublicationDate";
import type { ProjectUpdateInstructions } from "./projectUpdateInstructions";
import type { ProjectUpdateVoice } from "./projectUpdateVoice";

export interface ProjectUpdate {
  title: ProjectUpdateTitle;
  subtitle: ProjectUpdateSubtitle;
  purpose: ProjectUpdatePurpose;
  author: ProjectUpdateAuthor;
  publisher: ProjectUpdatePublisher;
  isbn: ProjectUpdateIsbn;
  language: ProjectUpdateLanguage;
  publication_date: ProjectUpdatePublicationDate;
  instructions: ProjectUpdateInstructions;
  voice: ProjectUpdateVoice;
}
