/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectInSubtitle } from "./projectInSubtitle";
import type { ProjectInPurpose } from "./projectInPurpose";
import type { ProjectInAuthor } from "./projectInAuthor";
import type { ProjectInPublisher } from "./projectInPublisher";
import type { ProjectInIsbn } from "./projectInIsbn";
import type { ProjectInLanguage } from "./projectInLanguage";
import type { ProjectInPublicationDate } from "./projectInPublicationDate";
import type { ProjectInInstructions } from "./projectInInstructions";
import type { ProjectInVoice } from "./projectInVoice";

export interface ProjectIn {
  title: string;
  subtitle?: ProjectInSubtitle;
  purpose?: ProjectInPurpose;
  author?: ProjectInAuthor;
  publisher?: ProjectInPublisher;
  isbn?: ProjectInIsbn;
  language?: ProjectInLanguage;
  publication_date?: ProjectInPublicationDate;
  instructions?: ProjectInInstructions;
  voice?: ProjectInVoice;
  has_images?: boolean;
}
