/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import type { SectionInIntroduction } from "./sectionInIntroduction";
import type { SectionInInstructions } from "./sectionInInstructions";
import type { SectionInOrder } from "./sectionInOrder";

export interface SectionIn {
  title: string;
  introduction?: SectionInIntroduction;
  instructions?: SectionInInstructions;
  order?: SectionInOrder;
}
