/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import type { SectionUpdateTitle } from "./sectionUpdateTitle";
import type { SectionUpdateIntroduction } from "./sectionUpdateIntroduction";
import type { SectionUpdateInstructions } from "./sectionUpdateInstructions";
import type { SectionUpdateOrder } from "./sectionUpdateOrder";

export interface SectionUpdate {
  title: SectionUpdateTitle;
  introduction: SectionUpdateIntroduction;
  instructions: SectionUpdateInstructions;
  order: SectionUpdateOrder;
}
