/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import type { SnapshotInName } from "./snapshotInName";
import type { SnapshotInDescription } from "./snapshotInDescription";
import type { SnapshotInSnapshot } from "./snapshotInSnapshot";

export interface SnapshotIn {
  name?: SnapshotInName;
  description?: SnapshotInDescription;
  snapshot?: SnapshotInSnapshot;
}
