/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import type { SnapshotOutName } from "./snapshotOutName";
import type { SnapshotOutDescription } from "./snapshotOutDescription";
import type { SnapshotOutSnapshot } from "./snapshotOutSnapshot";

export interface SnapshotOut {
  id: string;
  name: SnapshotOutName;
  description: SnapshotOutDescription;
  snapshot: SnapshotOutSnapshot;
  created_at: string;
}
