/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import type { SubsectionInContent } from "./subsectionInContent";
import type { SubsectionInInstructions } from "./subsectionInInstructions";
import type { SubsectionInOrder } from "./subsectionInOrder";

export interface SubsectionIn {
  title: string;
  content?: SubsectionInContent;
  instructions?: SubsectionInInstructions;
  order?: SubsectionInOrder;
}
