/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateFilesBodyDeleteFiles } from "./updateFilesBodyDeleteFiles";

export type UpdateFilesBody = {
  delete_files?: UpdateFilesBodyDeleteFiles;
  tarball: Blob;
};
