/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */

/**
 * Base URL for xAI API (defaults to https://api.x.ai)
 */
export type XAIModelsRequestBaseUrl = string | null;
