services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
      # careful, you can change your host config from inside the container
      - ${HOME}/.gitconfig:/home/vscode/.gitconfig
    environment:
      # DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
      PYTHONPATH: "/workspace/py/packages"
    depends_on:
      - db
    ports:
      - "8000:8000"
    # runs CMD from Dockerfile right now
    # entrypoint: "./.devcontainer/entrypoint.sh"

  db:
    build:
      context: .
      dockerfile: docker/Dockerfile.pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
