# Generated by Django 5.1.2 on 2025-06-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=500)),
                ("purpose", models.TextField(blank=True)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("isbn", models.CharField(blank=True, max_length=32)),
                ("language", models.CharField(default="en-US", max_length=10)),
                ("publication_date", models.DateField(blank=True, null=True)),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="System-level prompt to guide the LLM (tone, style, etc.)",
                    ),
                ),
                (
                    "voice",
                    models.TextField(
                        blank=True,
                        help_text='Narrative voice (e.g. "academic", "conversational")',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
