# Generated by Django 5.1.2 on 2025-06-23 04:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpora_commander", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                ("introduction", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="corpora_commander.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("project", "order")},
            },
        ),
        migrations.CreateModel(
            name="Subsection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="corpora_commander.section",
                    ),
                ),
            ],
            options={
                "ordering": ["section__order", "order"],
                "unique_together": {("section", "order")},
            },
        ),
    ]
