# Generated by Django 5.1.2 on 2025-07-15 22:22

import uuid

import django.db.models.deletion
from django.db import migrations, models

import corpora_commander.models


class Migration(migrations.Migration):

    dependencies = [
        ("corpora_commander", "0002_section_subsection"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image file to fulfill markdown placeholder caption",
                        upload_to=corpora_commander.models.project_image_upload_to,
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        help_text="Exact text matching the {{IMAGE: caption}} token",
                        max_length=1000,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="corpora_commander.project",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
                "unique_together": {("project", "caption")},
            },
        ),
    ]
