# Generated by Django 5.1.2 on 2025-06-22 16:44

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpora", "0008_alter_corpustextfile_vector_of_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corpus",
            name="url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional URL associated with the corpus, e.g., a GitHub repository.",
            ),
        ),
        migrations.AlterField(
            model_name="corpustextfile",
            name="vector_of_summary",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                editable=False,
                help_text="text-embedding-3-small vector of the content",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="split",
            name="vector",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                editable=False,
                help_text="text-embedding-3-small vector of the content",
                null=True,
            ),
        ),
    ]
