/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Corpora API
 * API for managing and processing corpora
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type { CorpusChatSchema, IssueSchema } from ".././schemas";

/**
 * @summary Get Issue
 */
export const getIssue = (
  corpusChatSchema: CorpusChatSchema,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IssueSchema>> => {
  return axios.default.post(
    `/api/corpora/plan/issue`,
    corpusChatSchema,
    options,
  );
};

export const getGetIssueMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof getIssue>>,
    TError,
    { data: CorpusChatSchema },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof getIssue>>,
  TError,
  { data: CorpusChatSchema },
  TContext
> => {
  const mutationKey = ["getIssue"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof getIssue>>,
    { data: CorpusChatSchema }
  > = (props) => {
    const { data } = props ?? {};

    return getIssue(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GetIssueMutationResult = NonNullable<
  Awaited<ReturnType<typeof getIssue>>
>;
export type GetIssueMutationBody = CorpusChatSchema;
export type GetIssueMutationError = AxiosError<unknown>;

/**
 * @summary Get Issue
 */
export const useGetIssue = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof getIssue>>,
      TError,
      { data: CorpusChatSchema },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof getIssue>>,
  TError,
  { data: CorpusChatSchema },
  TContext
> => {
  const mutationOptions = getGetIssueMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
