version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
      # - ${HOME}/.gnupg:/home/vscode/.gnupg
      - ${HOME}/.gitconfig:/home/vscode/.gitconfig:ro
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
      PYTHONPATH: "/workspace/py/packages"
      # GPG_TTY: "/dev/pts/0" # GPG_TTY configured
      # GNUPGHOME: "/home/vscode/.gnupg"
      # GPG_TTY: "$(tty)"
      # GNUPGHOME: "/root/.gnupg"
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: sleep infinity

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
