version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
      PYTHONPATH: "/workspace/py/packages"
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: sleep infinity

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
