name: Python CI

on:
  pull_request:
    paths:
      - 'py/**'
      - '.github/**'
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    services:
      postgres:
        image: ghcr.io/${{ github.repository_owner }}/postgres-pgvector:17
        # command: postgres -c listen_addresses=* -c port=5482
        ports:
          - 5482:5482
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          -c "postgres -c listen_addresses=* -c port=5482"

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r py/requirements.txt

      - name: Black
        run: black --check py/

      - name: Run tests with pytest
        env:
          PYTHONPATH: py/packages
          POSTGRES_HOST: localhost
        run: pytest py/
