name: CI Python

on:
  pull_request:
    paths:
      - 'py/**'
      - '.github/**'
      - 'devcontainer/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Dev Container and run commands
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/corpora-ci
          cacheFrom: ghcr.io/${{ github.repository }}/corpora-ci
          push: never
          runCmd: |
            docker compose --verbose -f .devcontainer/docker-compose.yaml up -d
            flake8 /workspace/py
            pytest /workspace/py

      - name: Capture Container Logs on Failure
        if: failure()
        run: |
          echo "Collecting logs from the app container..."
          docker compose -f .devcontainer/docker-compose.yaml logs app || true
