name: CI Python

on:
  pull_request:
    paths:
      - 'py/**'
      - '.github/**'
      - 'devcontainer/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Dev Container and run commands
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/corpora-ci
          cacheFrom: ghcr.io/${{ github.repository }}/corpora-ci
          push: never
          runCmd: |
            flake8 /workspace/py
            pytest /workspace/py
