name: Cross-Platform Rust Build

on:
  # Trigger the workflow on push to master and pull requests affecting the .github directory
  push:
    branches:
      - master
  pull_request:
    paths:
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cross
        working-directory: rs
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build the project using cross
        working-directory: rs
        run: cross build --release --target ${{ matrix.target }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}-binary
          path: rs/target/${{ matrix.target }}/release/<your-binary-name>
