name: Build and Push PostgreSQL with pgvector

on:
  # push:  # This will trigger on any branch push
  # for now can be manually triggered occasionally
  # gh auth login
  # gh workflow run .github/workflows/pgvector17.yml --ref main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image with pgvector
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/postgres-pgvector:17 -f docker/Dockerfile.pgvector .

      - name: Push image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/postgres-pgvector:17
