on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
# TODO: in the future we probably want to only run on demand
# on:
#   issue_comment:
#     types: [created]

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    # TODO: on demand at some point?
    # if: >
    #   github.event.issue.pull_request &&
    #   (github.event.comment.body == '/review' || github.event.comment.body == '/describe')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          # https://platform.openai.com/usage
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
